
["Stat 2"]
	#Defines if the stat is on or off
	"Stat 2" = true
	#Defines which name do you want to use for this stat in the menu
	"Stat 2 Name " = "Vitality"
	#Defines the ID of the attribute, example: minecraft:generic.attack_speed
	"Stat 2 ID" = "minecraft:generic.max_health"
	#The value added to the attribute per level
	"Stat 2 Value" = 0.5
	"Stat 2 Max" = 100.0
	"Max Stat2" = 0.0

[Misc]
	"Stat 2 Default Value" = 20.0

["Extra 1"]
	"Stat 2 Extra 1 ID" = "aaa:aaa2"
	"Stat 2 Extra 1 Value" = 0.1
	"Stat 2 Extra 1 LVL Req" = 1.0
	"Stat 2 Extra 1 Max" = 100.0

["Extra 2"]
	"Stat 2 Extra 2 ID" = "aw:awa"
	"Stat 2 Extra 2 Value" = 0.8
	"Stat 2 Extra 2 LVL Req" = 1.0
	"Stat 2 Extra 2 Max" = 3.0

["Extra 3"]
	"Stat 2 Extra 3 ID" = "ada:aaaa"
	"Stat 2 Extra 3 Value" = 4.0
	"Stat 2 Extra 3 LVL Req" = 5.0
	"Stat 2 Extra 3 Max" = 55.0

