
["Stat 5"]
	#Defines if the stat is on or off
	"Stat 5" = true
	#Defines which name do you want to use for this stat in the menu
	"Stat 5 Name " = "Magic"
	#Defines the ID of the attribute, example: minecraft:generic.attack_speed
	"Stat 5 ID" = "modid:attribute"
	#The value added to the attribute per level
	"Stat 5 Value" = 0.1
	"Stat 5 Max" = 100.0
	"Max Stat 5" = 0.0

["Extra 1"]
	"Stat 5 Extra 1 ID " = "irons_spellbooks:max_mana"
	"Stat 5 Extra 1 Value" = 1.0
	"Stat 5 Extra 1 LVL Req" = 1.0
	"Stat 5 Extra 1 Max" = 500.0

["Extra 2"]
	"Stat 5 Extra 2 ID" = "irons_spellbooks:spell_resist"
	"Stat 5 Extra 2 Value" = 0.1
	"Stat 5 Extra 2 LVL Req" = 40.0
	"Stat 5 Extra 2 Max" = 3.0

["Extra 3"]
	"Stat 5 Extra 3 ID" = "modid:attribute"
	"Stat 5 Extra 3 Value" = 0.1
	"Stat 5 Extra 3 LVL Req" = 1.0
	"Stat 5 Extra 3 Max" = 3.0

["Custom Mana"]
	"Custom Mana" = 0.0

