
[Overworld]
	#Choose a value between [0-99]
	lesser_drop_rate = 80.0
	#Choose a value between [0-99] you have to take into account the previous probabilities for exmaple (if the value = 80 which means its 90% its a better if not a lesser )
	better_drop_rate = 95.0
	#Choose a value between [0-99] & 99% chance guarantees the drop if the previous two drops were unsuccessful
	greater_drop_rate = 99.0

[Nether]
	#Choose a value between [0-99]
	lesser_drop_rate = 50.0
	#Choose a value between [0-99] you have to take into account the previous probabilities for exmaple (if the value = 80 which means its 95% its a better if not a lesser )
	better_drop_rate = 95.0
	#Choose a value between [0-99] & 99% chance guarantees the drop if the previous two drops were unsuccessful
	greater_drop_rate = 99.0

[End]
	#Choose a value between [0-99]
	lesser_drop_rate = 20.0
	#Choose a value between [0-99] you have to take into account the previous probabilities for exmaple (if the value = 80 which means its 90% its a better if not a lesser )
	better_drop_rate = 30.0
	#Choose a value between [0-99] & 99% chance guarantees the drop if the previous two drops were unsuccessful
	greater_drop_rate = 99.0

["Bosses Drop Rates"]
	#Max drop rate of orbs of leveling from bosses
	max_drop_rate = 3.0
	min_drop_rate = 1.0
	#list of the mobs which will drop the leveling orbs
	bosses_list = ["minecraft:ender_dragon", "minecraft:wither"]

